openapi: 3.0.1
info:
  title: Learn Express & Swagger
  description: A course segment about writing docs
  version: 1.1.0
  contact:
    email: yash.pundhir.prof@gmail.com
    url: "https://yash-pundhir-portfolio-sj.netlify.app/"

# servers:
#   - url: "http://localhost:4000/api/v1"
#     description: Local Host Version of the app - Regular
#   - url: "https://localhost:4000/api/v1"
#     description: Local Host Version of the app - Secure

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: Local Host Version of the app - {type}
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http
      type:
        enum:
          - Regular
          - Secure
        default: Regular

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie # in => come in from
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /lco:
    get:
      tags:
        - String
      summary: returns a greet message from LCO
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "myString"
        400:
          description: Bad Request
        500:
          description: Internal Server Error

  /lcoobject:
    get:
      tags:
        - Object
      summary: returns a course object
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
        400:
          description: Bad Request
        500:
          description: Internal Server Error
