openapi: 3.0.1
info:
  title: Learn Express & Swagger
  description: A course segment about writing docs
  version: 1.1.0
  contact:
    email: yash.pundhir.prof@gmail.com
    url: "https://yash-pundhir-portfolio-sj.netlify.app/"

# servers:
#   - url: "http://localhost:4000/api/v1"
#     description: Local Host Version of the app - Regular
#   - url: "https://localhost:4000/api/v1"
#     description: Local Host Version of the app - Secure

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: Local Host Version of the app - {type}
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http
      type:
        enum:
          - Regular
          - Secure
        default: Regular

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie # in => come in from
      name: token
    BearerAuth:
      type: http
      scheme: bearer
